language: python
python:
- '2.7'
install: pip install -r requirements.txt
script: python -m unittest discover
notifications:
  slack:
    secure: nVrlubOaXfaDqcQF0F4b17bZka2CudGJAK7I+aB6ILVurw12rbXIOaA4FiB22w7w+5gZKp3N5BL9LLUyPDZC5sv1xdNFKnakgbh47Gup7i6WG/xSZ7weyPOZwJFwQmjVv3YopDibp9qbuuuE/+lQBBSa/0EFFhdY65rSlAlQozlBRuoXMCumrEKv1zFu/yAJw9fRzK40hwICng+vHDgV9/rKCTOxtiXGzJZO3fJpsdNG1A1tEXi7tyaUqHBTHLoTdKKTWzjfUMriEYt8vRNCncUzB4Ox0e98q/gaTXVM/wkzu4MSRhZ/VTF9OrBnSujtTCSxq5fMJVhUiXaB+6sz8ljCzdk3U8On7JE4SBZl2xEuSwHzu1zaQgldAZPT5ouGAoAFriiS1Z8KcWpQADIyZwGTt9WAENIf/UZMoKIR9nN/MI6cF9RTYhYa8SbFoOL71CxWb5VvFzpJICqNapeCuwqo4d/P0qEerfYBY1PymdUTphZIyT/ZU2J6il4ADD/1rnXFNKUrfWl0b6YRu8JXuINVIuFRGThF3BCu5LspyBUnEM6uOBGiivUahZQgbxPJQrta6txKpa9U6BSBlYhyyyg9ooMAmPfWJgTLLtnTUihKvs09kNlfXerQIgDqOkSk037ZN5qdJ2EX3UBnLp17eYh2GSGps5KyTqvc65ZQDqc=
